### ISSUE TITLE
Getting Tracebacks on calling get_accel_data()

### ISSUE THREAD

**Issue by shreyasbapat** [Tijndagamer/MPU-6050-Python#21]
We are testing mpu6050 and are currently getting such tracebacks :  
``
  Traceback (most recent call last):

  File "balance.py", line 72, in <module>

    accel_data = sensor.get_accel_data()

  File "/usr/local/lib/python3.5/dist-packages/mpu6050/mpu6050.py", line 141, in get_accel_data

    z = self.read_i2c_word(self.ACCEL_ZOUT0)

  File "/usr/local/lib/python3.5/dist-packages/mpu6050/mpu6050.py", line 71, in read_i2c_word

    high = self.bus.read_byte_data(self.address, register)

OSError: [Errno 121] Remote I/O error
``

What can be the reason for these tracebacks? 
cc @manvi07

**Comment by m-rtijn** [comment]
Since you're getting an `Remote I/O error`, the first thing I would check is the connection with the sensor. Is i2c enabled on your device? Are you running as a user that has access to the i2c bus (try to run with `sudo` if you're not sure)? Are the physical connections with the sensors correct? Check the wires and solder joints.

**Comment by akshat157** [comment]
@shreyasbapat Thanks for posting the issue here and Thanks @Tijndagamer for the suggestions. I resolved those tracebacks by I think re-enabling the interfaces and reconnecting the sensor and the wires. Though we're still facing some problem. new tracebacks are -- 
![screenshot from 2018-05-14 22-28-16](https://user-images.githubusercontent.com/34815179/40018482-06fec8ca-57da-11e8-9695-d63245d2e3b6.png)

Where code mpu.py can be found here -http://www.electronicwings.com/raspberry-pi/mpu6050-accelerometergyroscope-interfacing-with-raspberry-pi

and that for balance.py - https://github.com/shivaay1/Equsant-Self-Balancing-Robot-Python/blob/master/equsant.py

EDIT: We fixed the error by replacing the jumper wires. Thanks for the help! :)
@shreyasbapat , you can close the issue now.

**Comment by shreyasbapat** [comment]
Thanks a lot! @Tijndagamer  for a Great library!

**Comment by m-rtijn** [comment]
Good to hear that it works now. I'm glad you like the library!
